export const VIDEOS = [
  {
    id: 1,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-1.jpg',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 2,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-2.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 3,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-3.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 4,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-4.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 5,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-5.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 6,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-6.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 7,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-7.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 8,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-8.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 9,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-9.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 10,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-10.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 11,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-11.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 12,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-12.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 13,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-13.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 14,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-14.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 15,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-15.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 16,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-16.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 17,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-17.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 18,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-18.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 19,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-19.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 20,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-20.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 21,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-21.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 22,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-22.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 23,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-23.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 24,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-24.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
  {
    id: 25,
    title: '⚛️ REACT + TYPESCRIPT: Creando un proyecto desde cero y paso a paso (Tutorial en español)',
    thumbnail: '/thumbnailsVideos/min-25.webp',
    url: 'https://www.youtube.com/watch?v=15VKbky2gB4',
    createdAt: 61851275450,
    views: 403681,
    authorAvatar: '/thumbnailsVideos/author.jpg',
    authorName: 'Midudev',
    authorUrl: 'https://www.youtube.com/c/midudev',
    duration: 150600,
  },
];
